- name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # ⚠️ 22 ではなく必ず 10022 にしてください
          port: 10022 
          
          local_path: './*'
          # ⚠️ 画像（image_04d424.png）のフルパスを指定
          remote_path: '/home/xs057242/kona-resort.jp/public_html/lp_data/holoholo202601/'
          
          args: '-o StrictHostKeyChecking=no'
